### ISSUE TITLE
Add DNS domain as an option to aq map_service

### ISSUE THREAD

**Issue by drossy** [quattor/aquilon#130]
I have two instances of the same service, both have the same personality and are in the same archetype and (virtual) rack and network, the only significant difference is the DNS domain name - is it possible to add DNS domain as an option to aq map_service?

**Comment by ned21** [comment]
Hi

We have considered this a few times and the conclusion was that it was difficult to implement without hardcoding assumptions about the meaning of DNS domain names. The service chooser is a Direct Acyclic Graph and so new attributes need to be given a precedence in that graph. For example, we previously used geographic ones (building1.example.com, building2.example.com) but we now have a new environment where domain names are Kerberos realms tied to environment (kryptonite.example.com, kryptonite-qa.example.com).

The other issue is that the service chooser is already extremely complex. I was recently tasked with trying to figure out why some hosts were choosing instance A instead of B. It took me a long while to realise how the geographic graph interacts with the non-geographic attributes, and it came down to the fact that I had configured the maps incorrectly, something I would almost certainly do wrong next time too if I hadn't made some notes on our internal wiki which I should probably share here at some point!

The other thing to consider is: are these truly clients of the service instance or are they servers? Because your use case sounds a lot like you have two servers of two different instances, in which case individual server selection via aq bind_server would already work for you. 

Cheers
Nathan
