### ISSUE TITLE
Feature Request - Add disk to model

### ISSUE THREAD

**Issue by apdibbo** [quattor/aquilon#27]
It would be very useful to be able to add additional disks to a model rather than having to do it individually at the machine level with aq add_disk

**Comment by jrha** [comment]
You can do this in the pan template for the model.

**Comment by ned21** [comment]
Our experience is that defining defaults at the model level is painful because a "model" is not consistent. e.g. vendors can tweak the CPU supplied, or the hardware team can choose to buy different SKUs within a single model.

Our approach has been to remove all defaults from models and script the addition of machines based on a "recipe" which can be customised by what is bought "this month".

@jrha is happy with workaround of defining these in PAN templates instead so closing this as won't fix as while we're not opposed to fixing it, realistically it will not happen.
