### ISSUE TITLE
IPv6 networks and addresses cannot be configured

### ISSUE THREAD

**Issue by jrha** [quattor/aquilon#42]
In particular `add_network` will not accept anything other than an IPv4 address.

**Comment by jrha** [comment]
@gombasg reported at March 2017 workshop that he has code that allows IPv6 networks and DNS entries to be created.

**Comment by urbonegi** [comment]
Lot of IPv6 support was enabled and sync to upstream during last couple of months. This is one of the main tag for this piece of work:
https://github.com/quattor/aquilon/releases/tag/1.12.40-rc1
@jrha can this be closed?

**Comment by jrha** [comment]
I think so, I'll review what was pushed to upstream and close this issue if it has been addressed.

**Comment by urbonegi** [comment]
This is one bug discovered by @jouvin which is constrain in network model that includes extra 'case' statement for ipv6. This needs to be moved to validate method for network model rather than be in DB constrains. New new DB initialization fails for postgresql.
https://github.com/quattor/aquilon/blob/upstream/lib/aquilon/aqdb/model/network.py#L147

**Comment by urbonegi** [comment]
@jrha can we close this one? There is a separate issue open for a bug in network model.

**Comment by jrha** [comment]
Yes, apologies for the delay.
