### ISSUE TITLE
1.12.58: empty hardware (model) templates should be made optional

### ISSUE THREAD

**Issue by jouvin** [quattor/aquilon#85]
Currently, it is necessary to create a template for each model, even if it is an empty template. This is quite tedious. The machine template should do the following:
* Use `if_exists()` with `include` statement, e.g.:
```
include if_exists("hardware/machine/dell/fc-20");
```
* Use a unique dummy template, which could be created by the broker if it doesn't exist, with `create` fundtion, e.g.:
```
RAM_TEMPLATE = if_exists("hardware/ram/generic");
RAM_TEMPLATE ?= "hardware/empty_structure_template";
);
"ram" = list(
  create(RAM_TEMPLATE 
    "size", 98304
  )
);
```

**Comment by ned21** [comment]
Actually this is a feature not a bug because prevents someone deploying un-certified hardware. Experimental hardware models get added and evaluated via `aq add_model` but that only allows you to use the hardware in a sandbox or non-prod domain. To get something into prod the hardware template must be deployed there via the usual process.

**Comment by jouvin** [comment]
@ned21 I completely agree! In fact, I realized that my report was wrong yesterday. My problem is a side effect of the hardware templates being executed before the template library loadpath is defined. I'll open a new issue about this.
