### ISSUE TITLE
Aquilon 1.12.58: /system/archetype/os in object template has the wrong type

### ISSUE THREAD

**Issue by jouvin** [quattor/aquilon#93]
In Aquilon 1.12.58, the broker still generate `/system/archetype/os` as a string according to the old schema. It was changed to a `dict` one year ago for the reasons explained in https://github.com/quattor/template-library-core/pull/142. The broker should adapt to the new schema, potentially with an option to ease the transition at MS.

This is **required for the template library support** in Aquilon (see https://github.com/quattor/template-library-core/pull/177). This is a subissue for #90.

**Comment by ned21** [comment]
hmm.. When quattor/template-library-core#142 was introduced it was explicitly called out that this did not require a change to aquilon because this was set in templates. Now it appears I wasn't aware that @jrha was using an older version of aqd which predates 3b82d80015 that should have blocked 
https://github.com/quattor/template-library-core/pull/142 from being merged.

So I think we need to go back and undo #142.

**Comment by jrha** [comment]
I've opened quattor/template-library-core#181 to revert the breaking changes from quattor/template-library-core#142, reverting the entirety of quattor/template-library-core#142 would be overkill.
